### ISSUE TITLE
Integration test 'Then' section exception for CreateCriteria

### ISSUE THREAD

**Issue by shiranr** [apache/grails-data-mapping#694]
Hi,

When using 'CreateCriteria' in the 'Then' section on an integration test, and exception is being thrown:
java.lang.IllegalStateException: No Datastore Session bound to thread, and configuration does not allow creation of non-transactional one here

```

java.lang.IllegalStateException: No Datastore Session bound to thread, and configuration does not allow creation of non-transactional one here

    at org.grails.datastore.mapping.core.DatastoreUtils.doGetSession(DatastoreUtils.java:149)
    at org.grails.datastore.mapping.core.AbstractDatastore.getCurrentSession(AbstractDatastore.java:141)
    at org.grails.datastore.gorm.mongo.MongoGormStaticApi.createCriteria(MongoGormStaticApi.groovy:52)
    at org.grails.datastore.gorm.GormEntity$Trait$Helper.createCriteria(GormEntity.groovy:432)
    at com.jfrog.reproduce.User.findProfile(User.groovy:10)
    at com.jfrog.reproduce.UserServiceIntegrationSpec.test something(UserServiceIntegrationSpec.groovy:30)
```

This is reproduced in userServiceIntegrationSpec in this project:
https://github.com/shiranr/reproduce5

As you can see, the FindAllBy command works perfectly but the create criteria list search does not.

Thanks,
Shiran.

**Comment by graemerocher** [comment]
The integration test is not marked with `@Transactional` or `@Rollback` and so lacks a session bound, hence the error. We don't have a transformation that wraps a session without a transaction at this stage.
